services:
  - type: web
    name: legal-faq-backend
    env: java              # This tells Render it's a Java app
    rootDir: backend       # Points to your backend folder
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free
